# -*- coding: utf-8 -*-
{
    "name": "Gestión de Calidad - Hexágonos Mexicanos",
    "version": "18.0.3.0.0",
    "category": "Manufacturing/Quality",
    "summary": "Gestión integral de calidad - Hexágonos (req. Feb-26)",
    "author": "Alphaqueb Consulting SAS",
    "website": "https://alphaqueb.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "sales_team",
        "web", "mail", "project", "mrp", "sale", "stock",
        "product", "contacts", "hr",
    ],
    "data": [
        "security/quality_groups.xml",
        "security/ir.model.access.csv",
        "security/quality_rules.xml",
        "data/sequence_data.xml",
        "data/process_type_data.xml",
        "data/quality_attribute_preset_data.xml",
        "data/quality_hardening_data.xml",
        "data/cron_data.xml",
        "wizards/certificate_wizard_views.xml",
        "views/quality_process_type_views.xml",
        "views/quality_attribute_template_views.xml",
        "views/quality_sample_release_views.xml",
        "views/quality_drawing_release_views.xml",
        "views/quality_inspection_views.xml",
        "views/quality_hardening_views.xml",
        "views/quality_certificate_views.xml",
        "views/quality_corrective_action_views.xml",
        "views/quality_customer_return_views.xml",
        "views/quality_customer_document_views.xml",
        "views/quality_dashboard_views.xml",
        "views/quality_troquel_views.xml",
        "views/res_company_views.xml",
        "views/product_views.xml",
        "views/quality_inherited_views.xml",
        "views/quality_menus.xml",
        "reports/report_quality_certificate.xml",
        "reports/report_8d.xml",
        "reports/report_inspection_summary.xml",
        "reports/report_sample_release.xml",
        "reports/report_drawing_release.xml",
        "reports/report_customer_return.xml",
        "reports/report_customer_document.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "quality_management/static/src/css/quality_pdf_viewer.css",
            "quality_management/static/src/css/quality_evidence_viewer.css",
            "quality_management/static/src/js/evidence_viewer_widget.js",
            "quality_management/static/src/xml/evidence_viewer_widget.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
