from . import quality_process_type
from . import res_company
from . import quality_attribute_template
from . import quality_sample_release
from . import quality_drawing_release
from . import quality_drawing_modification
from . import quality_inspection
from . import quality_inspection_line
from . import quality_inspection_ranurado
from . import quality_inspection_troquelado
from . import quality_certificate
from . import quality_corrective_action
from . import quality_action_line
from . import quality_5why
from . import quality_ishikawa
from . import quality_work_team
from . import quality_customer_return
from . import quality_customer_document
from . import quality_troquel
from . import quality_inherited_models
from . import product_template
from . import quality_hardening
