from . import quality_process_type
from . import quality_attribute_template
from . import quality_sample_release
from . import quality_drawing_release
from . import quality_inspection
from . import quality_inspection_line
from . import quality_inspection_ranurado
from . import quality_inspection_troquelado
from . import quality_certificate
from . import quality_corrective_action
from . import quality_action_line
from . import quality_customer_return
from . import quality_customer_document
from . import quality_inherited_models